### ISSUE TITLE
Null pointer on 2.0.0-M.4

### ISSUE THREAD

**Issue by marstonstudio** [stoicflame/enunciate#144]
I'm testing enunciate 2.0.0-M.4 on my Jersey2 project. I'm using this to do documentation only and do not need any client code generated. When I run the maven build I get a null pointer with the stack trace listed below, which appears to be related to the Csharp code generation. I've included my enunciate.xml config file here which should disable it.

```
<?xml version="1.0"?>
<enunciate label="bridge" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-1.30.xsd">

    <modules>
        <csharp disabled="true"/>
        <c disabled="true"/>
        <obj-c disabled="true"/>
        <jaxws disabled="true" />
        <docs   title="Bridge REST API"
                docsDir="target/bridge/documentation"
                includeExampleXml="false"
                includeExampleJson="true"
                forceExampleJson="true"
                includeDefaultDownloads="false"
                groupRestResources="com.babelcentral.services.bridge">
        </docs>
        <facets>
            <exclude name="com.babelcentral.services.excluded"/>
        </facets>
    </modules>

</enunciate>
```

```
DEBUG] [ENUNCIATE] Generating the C# client classes...
[DEBUG] [ENUNCIATE] Processing template jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt.
Sep 15, 2015 2:59:57 PM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> wsdls  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 10]

----
Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list wsdls as wsdl  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 3]
	- Reached through: @file name=csFileName charset="utf-8"  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 10, column 1]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:116)
	at freemarker.core.Expression.assertNonNull(Expression.java:188)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
	at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
	at freemarker.core.Environment.visit(Environment.java:377)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment.process(Environment.java:290)
	at freemarker.template.Template.process(Template.java:312)
	at com.webcohesion.enunciate.modules.csharp_client.CSharpXMLClientModule.processTemplate(CSharpXMLClientModule.java:595)
	at com.webcohesion.enunciate.modules.csharp_client.CSharpXMLClientModule.generateSources(CSharpXMLClientModule.java:327)
	at com.webcohesion.enunciate.modules.csharp_client.CSharpXMLClientModule.call(CSharpXMLClientModule.java:125)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:07.534s
[INFO] Finished at: Tue Sep 15 14:59:57 EDT 2015
[INFO] Final Memory: 102M/623M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:assemble (default) on project bridge: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:assemble failed: com.webcohesion.enunciate.EnunciateException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
[ERROR] ==> wsdls  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 10]
[ERROR] 
[ERROR] ----
[ERROR] Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[ERROR] ----
[ERROR] 
[ERROR] ----
[ERROR] FTL stack trace ("~" means nesting-related):
[ERROR] - Failed at: #list wsdls as wsdl  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 3]
[ERROR] - Reached through: @file name=csFileName charset="utf-8"  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 10, column 1]
[ERROR] ----
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:assemble (default) on project bridge: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:assemble failed: com.webcohesion.enunciate.EnunciateException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> wsdls  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 10]

----
Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list wsdls as wsdl  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 3]
	- Reached through: @file name=csFileName charset="utf-8"  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 10, column 1]
----
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:assemble failed: com.webcohesion.enunciate.EnunciateException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> wsdls  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 10]

----
Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list wsdls as wsdl  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 3]
	- Reached through: @file name=csFileName charset="utf-8"  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 10, column 1]
----
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> wsdls  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 10]

----
Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list wsdls as wsdl  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 3]
	- Reached through: @file name=csFileName charset="utf-8"  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 10, column 1]
----
	at com.sun.tools.javac.main.Main.compile(Main.java:469)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:650)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:352)
	at com.webcohesion.enunciate.mojo.AssembleBaseMojo.execute(AssembleBaseMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	... 20 more
Caused by: com.webcohesion.enunciate.EnunciateException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> wsdls  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 10]

----
Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list wsdls as wsdl  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 3]
	- Reached through: @file name=csFileName charset="utf-8"  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 10, column 1]
----
	at com.webcohesion.enunciate.modules.csharp_client.CSharpXMLClientModule.generateSources(CSharpXMLClientModule.java:333)
	at com.webcohesion.enunciate.modules.csharp_client.CSharpXMLClientModule.call(CSharpXMLClientModule.java:125)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> wsdls  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 10]

----
Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list wsdls as wsdl  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 18, column 3]
	- Reached through: @file name=csFileName charset="utf-8"  [in template "jar:file:/Users/jon/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.0.0-M.4/enunciate-csharp-xml-client-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/csharp_client/api.fmt" at line 10, column 1]
----
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:116)
	at freemarker.core.Expression.assertNonNull(Expression.java:188)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
	at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
	at freemarker.core.Environment.visit(Environment.java:377)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment.process(Environment.java:290)
	at freemarker.template.Template.process(Template.java:312)
	at com.webcohesion.enunciate.modules.csharp_client.CSharpXMLClientModule.processTemplate(CSharpXMLClientModule.java:595)
	at com.webcohesion.enunciate.modules.csharp_client.CSharpXMLClientModule.generateSources(CSharpXMLClientModule.java:327)
	... 27 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by stoicflame** [comment]
Fixed at 521f907.

FYI, the reason the csharp modules is still enabled is because some of the module names changed in M.4 to specify the syntax ( "csharp" is now "csharp-xml", etc). So you may want to adjust your config file like the following. 

Note the new schema URL, which would have highlighted the error.

Note also that the "jaxws" module isn't a client-side module; it's actually what processes the SOAP API, so if you have any SOAP endpoints, they won't otherwise show up in the docs. If you don't have any SOAP endpoints, the jaxws module is a no-op.

```xml
<?xml version="1.0"?>
<enunciate label="bridge" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.0.0.M.4.xsd">

    <modules>
        <csharp-xml disabled="true"/>
        <c-xml disabled="true"/>
        <obj-c-xml disabled="true"/>
        <docs   title="Bridge REST API"
                docsDir="target/bridge/documentation"
                includeExampleXml="false"
                includeExampleJson="true"
                forceExampleJson="true"
                includeDefaultDownloads="false"
                groupRestResources="com.babelcentral.services.bridge">
        </docs>
        <facets>
            <exclude name="com.babelcentral.services.excluded"/>
        </facets>
    </modules>

</enunciate>
```

**Comment by stoicflame** [comment]
Oh, also the "facets" element is in the wrong place. It should probably be moved under the root element (sibling to the `modules` element).

**Comment by marstonstudio** [comment]
Thanks!

Note that I get a 404 error at http://enunciate.webcohesion.com/schemas/enunciate-2.0.0.M.4.xsd so no luck with the schema hinting in IntelliJ

**Comment by stoicflame** [comment]
Doh! My bad. Forgot to push it. It should be there now.

**Comment by marstonstudio** [comment]
hmm, still getting 404 error at http://enunciate.webcohesion.com/schemas/enunciate-2.0.0.M.4.xsd

**Comment by stoicflame** [comment]
Dash before the "M" instead of a dot:

http://enunciate.webcohesion.com/schemas/enunciate-2.0.0-M.4.xsd
